### ISSUE TITLE
py-sblgnt version?

### ISSUE THREAD

**Issue by simoncozens** [jtauber/greek-reader#10]
In make_headwords, I am getting:

```
File "./make_headwords.py", line 39, in <module>
  for entry in get_morphgnt(verses, args.sblgnt_dir):
TypeError: get_morphgnt() takes 1 positional argument but 2 were given
```

If I remove the second argument I get:

```
File "./make_headwords.py", line 41, in <module>
  lexeme = entry[8]
IndexError: tuple index out of range
```

which makes me suspect that this is referring to a different (unreleased?) sblgnt version than the one which pip just installed for me.

**Comment by lucafavatella** [comment]
73c3b7c updated `py-sblgnt` in `requirements.txt` from 0.1 to 0.3: maybe it is worth testing again.

**Comment by jtauber** [comment]
We're now up to 0.5 and it's working fine for me so closing this.
